environment:
  matrix:
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - scoop bucket add southclaws https://github.com/Southclaws/scoops.git
  - scoop install sampctl
  - appveyor-retry choco install make
matrix:
  fast_finish: true

before_build:
  - make setup

build_script:
  - make release

test_script:
  - make run

artifacts:
  - path: plugins/samp_bcrypt.dll
    name: samp_bcrypt

deploy:
  - provider: BinTray
    username: Sreyas-Sreelal
    api_key:
      secure: avSVuY8Q8nSYesj3ce2v8cM6+aTSivkTzGozcCBMpJr+I0Td73+fVHTp6dAHcGw6
    subject: sreyas-sreelal
    repo: samp-bcrypt
    package: builds
    publish: true
    override: true
